### PR TITLE
Embedded thankyou page

### PR DESCRIPTION
**Pull request by alex-mo**
If a form is embedded via an iframe and `webform_ajax` loads the thank you page, then `X-Frame-Options` should be set.

### CODE REVIEW

**Comment by alex-mo** [comment]
Missing pieces:
- thankyou page needs to know it's embedded
- any links in the thankyou page should be opened in `target=_blank` (the embedded journey is done with the thankyou page)

**Comment by alex-mo** [comment]
the thankyou page now knows if it embedded, if a (checkbox) field named `field_pass_embed` is created on the action and is toggled on.

**Comment by alex-mo** [comment]
you will need to:
- allow `body` field to be displayed as CCK block
- create a context for the TY page, dependending on `current_webform_embedded` context which displays the `body` in the region `widget`
- check if the template `page--current-webform-embedded.tpl.php` is up-to-date (for the title to be displayed)

**Comment by torotil** [comment]
Thanks for the work and thoughts on this.

As discussed I don't intend to merge this unless we have a clear overall picture about how our widget is intended to work in the first place.

**Comment by alex-mo** [comment]
one more todo:
* multi step forms with webform_ajax currently break these patches

**Pull request closed without merging**
