### PR TITLE
Smaller bundle size for e2t app

### PR DESCRIPTION
**Pull request by dinony**
Just a low hanging fruit to get a smaller bundle.

**Now**
e2t_bunlde_now

**Previous**
e2t_bundle_prev

### CODE REVIEW

**Review by alex-mo — CHANGES_REQUESTED** [review]
I guess, you missed an import in `test/unit/specs/mutations.spec.js:4` :)

**Comment by alex-mo** [comment]
...but else: looking good to me! Thanks!

**Comment by alex-mo** [comment]
wow. that was quick! ;)

**Review by alex-mo — APPROVED** [review]

**Comment by dinony** [comment]
np :)

**Pull request merged**
