### PR TITLE
Add exporters more tailored towards exporting CSVs.

### PR DESCRIPTION
**Pull request by torotil**
Depends on #100

### CODE REVIEW

**Comment by alex-mo** [comment]
This is a rather big one, but from the look at the code: looks very good! :+1:

**Review by alex-mo — APPROVED** [review]

**Comment by torotil** [comment]
@alex-mo Sorry this PR is only about the exporters not the whole opt-in stuff.

**Comment by alex-mo** [comment]
^^

**Comment by torotil** [comment]
I think github is a bit confused with all the rebasing going on. The branch head is "Add CSV exporters."

**Pull request merged**
